export enum TodoActions {
  ADD_TODOS = 'ADD_TODOS',
  ADD_TODO = 'ADD_TODO',
  DELETE = 'DELETE',
  TOGGLE = 'TOGGLE',
  SET_PRELOADER_STATE = 'SET_PRELOADER_STATE',
  SET_ERROR_STATE = 'SET_ERROR_STATE',
}
